from typing import Iterator

class IntSpan:
    def __init__(self, *args, **kwargs) -> None: ...
    def __contains__(self, arg0: int) -> bool: ...
    def __getitem__(self, arg0: int) -> int: ...
    def __iter__(self) -> Iterator: ...
    def __len__(self) -> int: ...
